### ISSUE TITLE
Fenced code blocks rendered as single line

### ISSUE THREAD

**Issue by fxnut** [cjsheets/mkdocs-rtd-dropdown#3]
I seem unable to show more than a single line at a time in preformatted fenced code blocks.

Mark up written like this:
\```
line 1
line 2
\```
 Will always be rendered in HTML like this:
```
line 1 line 2
```

Having a play around, it seems that it's because the white-space CSS property for \<code\> is set to "nowrap", but even disabling that, newlines in the original markup seem to have been ignored.

**Comment by cjsheets** [comment]
It looks like this happened when I pulled in the latest CSS from the original ReadTheDocs theme. Thanks for pointing it out!

PR #4 should fix the issue. I also deployed the fix to Pypi so installing the latest version (0.0.9) would include the fix.

**Comment by fxnut** [comment]
Fantastic. Thanks for the quick fix! I can confirm that it's working now.
