### ISSUE TITLE
yml parameter for foldes states by default

### ISSUE THREAD

**Issue by Serhioromano** [cjsheets/mkdocs-rtd-dropdown#5]
Right now when I open link, it open all submenus unfolded. I would like to keem them folded and user will unfold what he wants.

Can you add an option for yml config?

**Comment by cjsheets** [comment]
Sorry for the delayed response. I think that's a good idea. I'll add it to the next version.

**Comment by cjsheets** [comment]
I just merged a number of bugfixes including the addition of a `collapse_by_default` theme setting.
